### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by dean0x7d**
@wjakob CMake v3.1 is now set as the minimum version for Windows because this is the oldest version which supports Visual Studio 2015. The `>= 3.1` requirement is stated in the readme and `setup.py` checks for it. I don't think this will be a problem since it was effectively always the minimum due to VS2015 support. There's just and explicit check for it now.

### CODE REVIEW

**Comment by wjakob** [comment]
I'd like to leave the 2.8.x version on Linux because the Ubuntu LTS releases still use that. Can there be a platform specific min. platform requirement?

**Comment by wjakob** [comment]
aha, looks like you're doing that in any case

**Comment by dean0x7d** [comment]
Yeah, it's platform-specific. `setup.py` will only do the `>-3.1` check on Windows. The 2.8.12 min version in `CMakeLists.txt` applies to all platforms.

**Comment by dean0x7d** [comment]
AppVeyor seems to broken. It's not checking this PR.

**Comment by dean0x7d** [comment]
It looks like AppVeyor didn't handle the repo transfer as well as Travis, but I'm not sure how to fix it. @wjakob Do you have any idea what could be happening there?

**Comment by wjakob** [comment]
I think I had to recreate the appveyor project profile when I moved pybind a while ago.

**Pull request merged**
